info:
  contact: {}
  description: Ceci est la documentation de l’API Harvest Hub.
  termsOfService: http://swagger.io/terms/
  title: Harvest Hub API
  version: "1.0"
paths:
  /ping:
    get:
      description: Vérifie que l’API fonctionne en renvoyant "pong"
      produces:
      - text/plain
      responses:
        "200":
          description: pong
          schema:
            type: string
      summary: Route de test (ping)
      tags:
      - test
swagger: "2.0"
