services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/garden_db?sslmode=disable
    depends_on:
      - db

  db:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_DB: garden_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - timescale_data:/var/lib/postgresql/data

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    environment:
      - SWAGGER_JSON=/docs/api.swagger.json
    volumes:
      - ./gen/openapiv2:/docs
    depends_on:
      - api

volumes:
  timescale_data:
