# Per-target settings; we don't set a global build.target so host simulation works with plain `cargo run`.
[target.thumbv7m-none-eabi]
runner = "probe-rs run --chip STM32F103C8Tx"
rustflags = ["-C", "link-arg=-Tlink.x"]
