name: Mirror commits to another repo

on:
  push:
    branches:
      - main  # or your branch

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false  # IMPORTANT: disable default GITHUB_TOKEN auth

      - name: Configure Git
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_GRIMALDEV_HARVESTHUB }}@github.com/EpitechMscProPromo2026/T-ESP-800-project-71769-STG_OH-MAX.git

      - name: Verify remote URL
        run: git remote -v

      - name: Test API Access
        run: |
          curl -H "Authorization: token ${{ secrets.PAT_GRIMALDEV_HARVESTHUB }}" https://api.github.com/repos/EpitechMscProPromo2026/T-ESP-800-project-71769-STG_OH-MAX

      - name: Filter out workflow files from history
        run: |
          git filter-branch --force --index-filter 'git rm --cached --ignore-unmatch -r .github/workflows/' --prune-empty --tag-name-filter cat -- --all
          git push origin HEAD:main --force

