name: Mirror commits to another repo

on:
  push:
    branches:
      - main  # or your branch

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git user
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Add target repo remote
        run: |
          git remote add target https://x-access-token:${{ secrets.PAT }}@github.com/EpitechMscProPromo2026/T-ESP-800-project-71769-STG_OH-MAX.git

      - name: Push to target repo preserving commit history
        run: |
          git push target HEAD:main --force
